fix failure due to python library internals changing (#1)
Attempting to migrate our data pipeline onto a freshly built server
resulted in our Salesforce integration failing:

```
Traceback (most recent call last):
  File "/opt/ga/ga-flask/redshift/load_logger.py", line 105, in run_and_step
    res = func(**args)
  File "/opt/ga/ga-flask/redshift/load_stg_salesforce.py", line 68, in load_stg_sf_table
    df = hlp.read_sf(tbl, updated_after=last_upd[0], limit=limit, order=True)
  File "/opt/ga/ga-flask/helper.py", line 512, in read_sf
    lg = bsf.login(sf_user, (sf_pswd+sf_sec_tok))
  File "/opt/ga/virtualenvs/alpha-server/local/lib/python2.7/site-packages/beatbox/python_client.py", line 73, in login
    res = BaseClient.login(self, username, passwd)
  File "/opt/ga/virtualenvs/alpha-server/local/lib/python2.7/site-packages/beatbox/_beatbox.py", line 60, in login
    lr = LoginRequest(self.serverUrl, username, password).post()
  File "/opt/ga/virtualenvs/alpha-server/local/lib/python2.7/site-packages/beatbox/_beatbox.py", line 309, in post
    conn.request("POST", path, self.makeEnvelope(), headers)
  File "/opt/ga/virtualenvs/alpha-server/local/lib/python2.7/site-packages/beatbox/_beatbox.py", line 266, in makeEnvelope
    s = SoapWriter()
  File "/opt/ga/virtualenvs/alpha-server/local/lib/python2.7/site-packages/beatbox/_beatbox.py", line 243, in __init__
    self.startElement(_envNs, "Envelope")
  File "/opt/ga/virtualenvs/alpha-server/local/lib/python2.7/site-packages/beatbox/_beatbox.py", line 177, in startElement
    self.xg.startElementNS((namespace, name), name, attrs)
  File "/opt/ga/virtualenvs/alpha-server/local/lib/python2.7/site-packages/beatbox/_beatbox.py", line 146, in startElementNS
    self._out.write('<' + self.makeName(name))
AttributeError: BeatBoxXmlGenerator instance has no attribute '_out'
```

Scouring the internet, I found the following issue:
- Github Issue: https://github.com/ebottabi/salesforce-beatbox/issues/14
- Original Google Code Issue: https://code.google.com/archive/p/salesforce-beatbox/issues/14

This problem has been known since the summer of 2013, and the beatbox
maintainers have not made a 20.1 release to no longer *depend upon the
xml.sax library internals*, which have changed in some recent version
of Python 2.7.

Attempting to upgrade to either the 32.0 or 32.1 version of the library
has netted other errors.

So, to resolve this issues in the most expedient manner, we are taking
the kludge recommended in the last comment of the thread: add
`self._out = destination` as line 137.

Server where the library functions normally:
- Ubuntu 12.04.5 LTS
- Python 2.7.3

Server where the libary is failing:
- Ubuntu 16.04.2 LTS
- Python 2.7.12

Testing process:
- I modified the VIRTUALENV/local/lib/python2.7/site-packages/beatbox/_beatbox.py file directly, adding this line of code
- I also added some debug output to verify non-empty responses
- I ran the script that downloads data from our Salesforce instance
- The script now functions as expected